### ISSUE TITLE
Compare system test results automatically 

### ISSUE THREAD

**Issue by potiuk** [GoogleCloudPlatform/oozie-to-airflow#141]
We need to have infrastructure setup to automatically run Oozie and Composer workflows from examples and compare their output as part of Travis CI tests.

**Comment by sprzedwojski** [comment]
While implementing this, we should fix the issue of DistCp not running on Oozie.
It works fine when ran manually via `hadoop distp` and using Airflow, the problem is only when running via Oozie.

Details here: https://docs.google.com/document/d/1UNhnWRQaqrZtGpNLNaICOdP_JyiaRSd-XIx6NirLFDg/edit?usp=sharing

**Comment by sprzedwojski** [comment]
Done in #298
