### ISSUE TITLE
Organize unit and integration tests. (0/1)

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#174]
Hello,

Integration and unit tests are in one file. This makes it difficult to understand their intentions.
Example: 
https://github.com/GoogleCloudPlatform/cloud-composer/blob/94b8a28/oozie-to-airflow/tests/converter/test_oozie_parser.py#L402-L527

It would be a fairy tale if the unit tests were separated from the unit ones

Thanks

**Comment by potiuk** [comment]
Fully agree. 

Let's first define criteria what the unit/integration/system tests mean for us and what are the criteria - because they are not obvious. Nor clear. @mik-laj  -> maybe you can propose these criteria and propose how we can split the tests (based on classes/files/packages?).

We should start with defining the three cases in documentation:
* what are unit tests
* what are integration tests
* what are system tests

For now we have "unit tests" (defined by using unit test frameworks) and system tests (defined by running oozie and composer examples on real Dataproc/Composer combo.
