### ISSUE TITLE
Implement framework to handle non-basic functions (0/5)

### ISSUE THREAD

**Issue by potiuk** [GoogleCloudPlatform/oozie-to-airflow#179]

**Comment by sprzedwojski** [comment]
Meeting minutes 20.05:
* We will do a spike using [Lark](https://github.com/lark-parser/lark) using BNF syntax

**Comment by nuclearpinguin** [comment]
Non determinism mentioned in https://github.com/GoogleCloudPlatform/oozie-to-airflow/pull/253#discussion297706016 could be related to resolving ambiguity in Lark.

**Comment by nuclearpinguin** [comment]
As a next step I would like to start evaluating Jinja templates. I see two possible approaches:

### 1) Render functions as functions
This approach proposes to translate `${concat('aaa', 'bbb')}` as `{{functions.concat('aaa', 'bbb'). Then all needed functions are located in a `functions` module which is passed to global Jinja variables.

In this approach we can use Jinja `@contextfunction` to access context variables, for example:
```python
@contextfunction
def wf_id(context):
    return context['run_id']
```
Then `${wf:id()}` is translated to `{{functions.wf_id()}}` which evaluates to `{{'ruuuun'}}`
 if `context['run_id'] = 'ruuuun'`.

The shortcomings of this approach are functions which require global arguments:
```python
def wf_error_code(node):
    """
    It returns the error code for the specified action node, or an empty string if
    the action node has not exited with ERROR state.
    """
```
For example `${wf:ErrorCode(node_name)}` is translated as `{{functions.wf_error_code(node_name)}}` and then we needs two argument for evaluation: `functions` and `node_name`.

### 2) Second option
Other option is to translate functions to equivalent variables / functions. For example:
```
${concat('aaa', 'bbb')} -> {{'aaa' ~ 'bbb'}}
${wf:id()} -> {{run_id}}
```
Here the translation would be done on the level of AST tree translation. This approach can help dealing with additional variables because the previous example could be translated as:
`${wf:ErrorCode(node_name)} -> {{functions.get_error()}}`


@mik-laj  @potiuk what are your thoughts?

**Comment by mik-laj** [comment]
I think, best options is 2.  We should convert everything to the format closest to the natural one. This is possible by using full parsing and it is worth using it.

**Comment by potiuk** [comment]
I agree with Kamil. It will be much better to use option 2) - but only if it is not overly complex to implement. It does not seem to be super-complex, but we should try it in one case and see if it will not slow us down. @nuclearpinguin

**Comment by nuclearpinguin** [comment]
Finally I think that the solution will be a mix of those two approaches. So, if the transformation could be seen as a string conversion and there is simple airflow equivalence for a function, we will use it :
- `wf:id() -> run_id`
- `wf:name() -> dag.dag_id`
- `concat(a, b) -> a ~ b`
- `trim(a) - > a.strip()`
- `timestamp() -> macros.datetime.now().strftime("%Y-%m-%dT%H:%M:%S.%fZ")`

But in a case when context variables are uses and when function evaluation is needed (or external import) the translation will be done with using function from `functions` module.

And one question: Am I right that variables defined in `job.properties` are accessible during template evaluation? @mik-laj

**Comment by sprzedwojski** [comment]
Yes, variables from `job.properties` are rendered in the DAG as a dict `JOB_PROPS`, e.g.
```
JOB_PROPS = {
    "user.name": "szymon",
    "nameNode": "hdfs://localhost:8020",
    "resourceManager": "localhost:8032",
    "queueName": "default",
    "examplesRoot": "examples",
    "userName": "szymon",
    "oozie.wf.application.path": "/user/szymon/examples/apps/git",
    "oozie.use.system.libpath": "true",
}
```

So they are available during Jinja template evaluation. If that's what you're asking about ;)

**Comment by nuclearpinguin** [comment]
@sprzedwojski that's exactly what I wanted to know! So if I fully understand `{{JOB_PROPS['user.name']}}` should evaluate to `szymon`?

**Comment by sprzedwojski** [comment]
As we discussed offline, the dict must be provided for Jinja.
In Airflow you can do it via the `params` argument for a Task.
We usually do it like this when creating tasks in O2A:
```
params=PropertySet(config=CONFIG, job_properties=JOB_PROPS).merged
```

Then in Jinja we should be able to access a key like:
```
{{ params.userName }}
```
and possibly also:
```
{{ params["userName"] }}
```
