### ISSUE TITLE
Rename ParsedActionNode to ParsedNode/OozieNode/etc

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/oozie-to-airflow#323]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when class name does not describe its purpose.
This class is also used to store information from control nodes, so the name is misleading.
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/master/o2a/converter/workflow_xml_parser.py#L90-L91
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/master/o2a/converter/workflow_xml_parser.py#L110-L111
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/master/o2a/converter/workflow_xml_parser.py#L146-L147
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/master/o2a/converter/workflow_xml_parser.py#L178-L185
https://github.com/GoogleCloudPlatform/oozie-to-airflow/blob/master/o2a/converter/workflow_xml_parser.py#L259-L267

**Describe the solution you'd like**
I would like this class to be called differently. 
My proposition:
* ``ParsedNode``
* ``OozieNode``

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sprzedwojski** [comment]
I support the idea 100%, however I'm not sure the proposed names correctly show what they would represent.
That's because actually both the control and action nodes, when parsed in O2A, are a "Parsed node" and an "Oozie node".

To me the biggest distinction is in whether the node is a "control" or an "action" node.
Therefore I'd suggest the following variants:

1. `ParsedActionNode`, `ParsedControlNode`
2. `OozieActionNode`, `OozieControlNode`
3. `ActionNode`, `ControlNode`

**Comment by sprzedwojski** [comment]
I think we should do this soon. It's going to be a rather quick change and I'm going to need it for https://github.com/GoogleCloudPlatform/oozie-to-airflow/issues/279 (notifications behave differently when transition between `control_node` -> `control_node`, e.g. join -> decision, than when between `action_node` -> `action_node`, e.g. mapreduce -> hdfs).

**Comment by potiuk** [comment]
My personal preference:  OozieActionNode/OozieControlNode

**Comment by potiuk** [comment]
I moved it to Charlie milestone ;)

**Comment by sprzedwojski** [comment]
Done in #330
